import { createFileRoute } from "@tanstack/react-router";
import type { ReactNode } from "react";

export const Route = createFileRoute("/")({
  component: HomePage,
});

function HomePage(): ReactNode {
  return (
    <main id="main-content">
      {/* Homepage content will be generated by codegen-pages */}
      <div className="flex min-h-[60vh] items-center justify-center px-4">
        <p className="text-[var(--color-text-muted)] font-body text-sm">
          Calzoleria Prevenzano
        </p>
      </div>
    </main>
  );
}
